11-01 09:44 - [INFO] (export.py).<module>(15) - Формируем:Pharmit
11-01 09:44 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./export/pharmit/
11-01 09:44 - [INFO] (system.py).clear_export_path(52) - Удаленно 0 файлов
11-01 09:44 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./log/
11-01 09:44 - [INFO] (system.py).clear_export_path(52) - Удаленно 0 файлов
11-01 09:44 - [INFO] (engine.py).wrapper(33) - Выполняю: create, 'file'
11-01 09:44 - [INFO] (engine.py).create(172) - .\export\file
11-01 09:44 - [INFO] (engine.py).create(185) - Загружаю алгоритм выгрузки:Pharmit
11-01 09:44 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 3815937500121 - 20210201 - Аптека №1 родионова - Терафлю Лимон N14 Пак - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 3822387512981 - 20210201 - Аптека №1 родионова - Релиф Мазь 28,4г - Catched error: Input string was not in a correct format. 

11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

11-01 09:44 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 1214104932 - 20210201 - Аптека №2 Белое - Ибуклин Юниор Таб Дисперг (Д/Дет) 100мг 125мг N20 - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 1221105142 - 20210201 - Аптека №2 Белое - ДЖОНСОНС ПРИСЫПКА ДЕТСКАЯ С КУКУРУЗНЫМ КРАХМАЛОМ ФЛ. 113Г - Catched error: Input string was not in a correct format. 

11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

11-01 09:44 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 09:44 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 219762103 - 20210201 - Аптека №3 Каменка - Цетрин Таб п/о 10мг N30 - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 220062173 - 20210201 - Аптека №3 Каменка - Називин спрей наз 22,5мкг/доза 10мл - Catched error: Input string was not in a correct format. 

11-01 09:44 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

