11-01 10:25 - [INFO] (export.py).<module>(15) - Формируем:Pharmit
11-01 10:25 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./export/pharmit/
11-01 10:25 - [INFO] (system.py).clear_export_path(52) - Удаленно 0 файлов
11-01 10:25 - [INFO] (system.py).clear_export_path(39) - Удаляем старые выгрузки в - ./log/
11-01 10:25 - [INFO] (system.py).clear_export_path(52) - Удаленно 0 файлов
11-01 10:25 - [INFO] (engine.py).wrapper(33) - Выполняю: create, 'file'
11-01 10:25 - [INFO] (engine.py).create(172) - .\export\file
11-01 10:25 - [INFO] (engine.py).create(185) - Загружаю алгоритм выгрузки:Pharmit
11-01 10:25 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 3821357509741 - 20210202 - Аптека №1 родионова - Омез капс. 20мг №30 - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 3821287509551 - 20210202 - Аптека №1 родионова - Спазмалгон Таб N20 - Catched error: Input string was not in a correct format. 

11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

11-01 10:25 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 1303106262 - 20210202 - Аптека №2 Белое - ПЕДИАШУР МАЛОЕЖКА 1-10 ЛЕТ 200МЛ ФЛАК/КЛУБНИКА - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 1295107242 - 20210202 - Аптека №2 Белое - РЕНЮ MultiPlus 240 мл. с контейн. д/конт. линз - Catched error: Input string was not in a correct format. 

11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

11-01 10:25 - [INFO] (system.py).existPath(59) - Каталог -./export/pharmit/ найден
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TABLE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - PROCEDURE
11-01 10:25 - [ERROR] (engine.py).cheak_db(65) - Нет параметров для проверки - TRIGGER
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
"Данные за эту дату уже загружены!"
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-200- OK-
[]
11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-400- Bad Request-
Пакет № 1; ProviderSaleId = 229063703 - 20210202 - Аптека №3 Каменка - Лазолван Фито сироп фл. 100 мл  - Catched error: Input string was not in a correct format. 
Пакет № 2; ProviderSaleId = 229463743 - 20210202 - Аптека №3 Каменка - Риномарис спрей наз. 0,1% фл. 15 мл - Catched error: Input string was not in a correct format. 

11-01 10:25 - [INFO] (pharmit.py).send_request(44) - https://api.pharmit.kz/api/loadhistories-500- Internal Server Error-

